#!/usr/bin/env python3
"""
scan_coderefs.py — Scans source files for \\coderef{name} tags and generates
a JSON database and a LaTeX definitions file.

Usage:
    python scan_coderefs.py ./src
    python scan_coderefs.py ./src --extensions "*.cpp" "*.h" "*.py" "*.f90"
"""

import argparse
import json
import re
import sys
from pathlib import Path

CODEREF_PATTERN = re.compile(r'\\coderef\{([^}]+)\}')


def latex_escape(s: str) -> str:
    """Escape special LaTeX characters in a file path string."""
    replacements = [
        ('\\', r'\textbackslash{}'),
        ('#',  r'\#'),
        ('$',  r'\$'),
        ('%',  r'\%'),
        ('&',  r'\&'),
        ('_',  r'\_'),
        ('{',  r'\{'),
        ('}',  r'\}'),
        ('~',  r'\textasciitilde{}'),
        ('^',  r'\textasciicircum{}'),
    ]
    for char, repl in replacements:
        s = s.replace(char, repl)
    return s


def scan_files(source_dir: Path, extensions: list[str]) -> dict:
    """
    Scan source_dir recursively for \\coderef{name} tags.

    Returns:
        { tag_name: [{"file": str, "line": int}, ...], ... }
        File paths are relative to source_dir, using forward slashes.
    """
    database: dict[str, list[dict]] = {}

    for ext in extensions:
        for filepath in sorted(source_dir.rglob(ext)):
            try:
                with open(filepath, encoding='utf-8', errors='replace') as f:
                    for lineno, line in enumerate(f, start=1):
                        for name in CODEREF_PATTERN.findall(line):
                            name = name.strip()
                            entry = {
                                "file": filepath.relative_to(source_dir).as_posix(),
                                "line": lineno,
                            }
                            database.setdefault(name, []).append(entry)
            except OSError as e:
                print(f"Warning: cannot read {filepath}: {e}", file=sys.stderr)

    return database


def generate_latex(database: dict, output_path: Path) -> None:
    """Write a LaTeX definitions file from the tag database."""
    lines = [
        "% Auto-generated by scan_coderefs.py — do not edit by hand.",
        "% Regenerate with: python scan_coderefs.py <source_dir>",
        "",
    ]
    for name, refs in sorted(database.items()):
        lines.append(f"\\coderefsetcount{{{name}}}{{{len(refs)}}}")
        for idx, ref in enumerate(refs, start=1):
            escaped_file = latex_escape(ref["file"])
            lines.append(
                f"\\coderefsetentry{{{name}}}{{{idx}}}"
                f"{{{escaped_file}}}{{{ref['line']}}}"
            )
        lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description=r"Scan source files for \coderef{name} tags."
    )
    parser.add_argument("source_dir", help="Root directory to scan recursively.")
    parser.add_argument(
        "--extensions", "-e", nargs="+", metavar="GLOB",
        default=["*.py", "*.cpp", "*.cc", "*.cxx", "*.c",
                 "*.h", "*.hpp", "*.f90", "*.f", "*.f77", "*.F90"],
        help="File glob patterns to scan. Default: %(default)s",
    )
    parser.add_argument(
        "--json-output", "-j", default="coderef_db.json", metavar="FILE",
        help="Output JSON file. Default: %(default)s",
    )
    parser.add_argument(
        "--latex-output", "-l", default="coderef_defs.tex", metavar="FILE",
        help="Output LaTeX definitions file. Default: %(default)s",
    )
    args = parser.parse_args()

    source_dir = Path(args.source_dir).resolve()
    if not source_dir.is_dir():
        print(f"Error: '{source_dir}' is not a directory.", file=sys.stderr)
        sys.exit(1)

    print(f"Scanning: {source_dir}")
    print(f"Extensions: {args.extensions}")

    database = scan_files(source_dir, args.extensions)

    # ── Duplicate tag check ───────────────────────────────────────────────────
    duplicates = {
        name: refs for name, refs in database.items() if len(refs) > 1
    }
    if duplicates:
        lines = ["Error: duplicate \\coderef tags found:"]
        for name, refs in sorted(duplicates.items()):
            lines.append(f"  '{name}' defined {len(refs)} times:")
            for ref in refs:
                lines.append(f"    {ref['file']}:{ref['line']}")
        print("\n".join(lines), file=sys.stderr)
        sys.exit(1)
    # ─────────────────────────────────────────────────────────────────────────

    if not database:
        print("Warning: no \\coderef tags found.", file=sys.stderr)

    json_path = Path(args.json_output)
    json_path.write_text(json.dumps(database, indent=2), encoding="utf-8")
    print(f"JSON database → {json_path}  ({len(database)} unique tags)")

    latex_path = Path(args.latex_output)
    generate_latex(database, latex_path)
    print(f"LaTeX defs    → {latex_path}")


if __name__ == "__main__":
    main()
